name: cine_libre
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Versión compatible de YouTube Player que no usa flutter_inappwebview
  youtube_player_iframe: ^4.0.4
  
  # Otras dependencias
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.2
  http: ^1.1.0
  
  # Firebase con versiones compatibles
  firebase_core: ^2.13.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.8.0
  
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/