// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsD1bVGbRvFV3kqtX8qglmt85TfXe6C54',
    appId: '1:822634328388:web:6b1d0ffcc3085e868a6711',
    messagingSenderId: '822634328388',
    projectId: 'cinelibre-f1b3a',
    authDomain: 'cinelibre-f1b3a.firebaseapp.com',
    storageBucket: 'cinelibre-f1b3a.firebasestorage.app',
    measurementId: 'G-7NGEJL5N6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnQSZhtclSyNiZquqqfTxcAclHjqsNxkk',
    appId: '1:822634328388:android:02174bf28a516e2d8a6711',
    messagingSenderId: '822634328388',
    projectId: 'cinelibre-f1b3a',
    storageBucket: 'cinelibre-f1b3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDudjgL6eonXqSEYqTOvP65YQNIIbm_-8s',
    appId: '1:822634328388:ios:b00af32b7f23616c8a6711',
    messagingSenderId: '822634328388',
    projectId: 'cinelibre-f1b3a',
    storageBucket: 'cinelibre-f1b3a.firebasestorage.app',
    iosBundleId: 'com.example.cineLibre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDudjgL6eonXqSEYqTOvP65YQNIIbm_-8s',
    appId: '1:822634328388:ios:b00af32b7f23616c8a6711',
    messagingSenderId: '822634328388',
    projectId: 'cinelibre-f1b3a',
    storageBucket: 'cinelibre-f1b3a.firebasestorage.app',
    iosBundleId: 'com.example.cineLibre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsD1bVGbRvFV3kqtX8qglmt85TfXe6C54',
    appId: '1:822634328388:web:46b35c0a23ffa0ae8a6711',
    messagingSenderId: '822634328388',
    projectId: 'cinelibre-f1b3a',
    authDomain: 'cinelibre-f1b3a.firebaseapp.com',
    storageBucket: 'cinelibre-f1b3a.firebasestorage.app',
    measurementId: 'G-PZCRG79LZH',
  );
}
